development:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
production:
  server: "http://1m-clinic.com.ua:9292/faye"
  secret_token: "cfd3fc4bfdb3c285f2892436e2cbaf747acc178e54af3a6ccc69f1524c00192e"
  signature_expiration: 2628000 # one month
